** Import git changes up to 2.6.29 merge **
commit 82670a7d050e5001f723a056e4827750c0f65dfc
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Sat Mar 28 19:57:29 2009 +0100

    gamecube: update defconfig

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/configs/gamecube_defconfig |   72 +++++++++++++++++++++---------
 1 files changed, 50 insertions(+), 22 deletions(-)

commit e28f75ea563c7c9e3fdec767ce029b4b1803172b
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Sat Mar 28 19:48:31 2009 +0100

    wii: update defconfig

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/configs/wii_defconfig |  167 ++++++++++++++++++++++++++++++------
 1 files changed, 140 insertions(+), 27 deletions(-)

commit 51a7be2130487abc9f47dc201d55b8049b0e8fba
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Wed Mar 25 19:28:44 2009 +0100

    wii: kexec: save/restore lowmem stub

    Add a save/restore mechanism to preserve the lowest 16KiB of memory and make
    them available again after a kexec reboot.

    This is useful to preserve the "resident" reloader stubs installed by
    the existing bootloaders.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/boot/dts/wii.dts            |    6 +++
 arch/powerpc/boot/wii.c                  |   38 ++++++++++++++++++++++
 arch/powerpc/platforms/embedded6xx/wii.c |   51 +++++++++++++++++++++++++++++-
 3 files changed, 94 insertions(+), 1 deletions(-)

commit 0dc2ea8a60ff7f96091393d999add383f3d15cbf
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Wed Mar 25 18:13:12 2009 +0100

    kexec: add preserved region

    This patch allows kexec to copy back a previously preserved memory region
    to its original location at kexec time.

    For example, the preserved region can be saved during boot time to a safe
    area and then restored back during the final kexec phase.

    The caller is responsible to ensure that the destination memory area can
    be safely overwritten. The source memory area must be available during
    the kexec relocation stage.

    One immediate use is preserving the lowest 16KiB in the Nintendo GameCube
    and Wii video game consoles which are traditionally used to host reloader
    stubs.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 include/linux/kexec.h |   11 +++++++----
 kernel/kexec.c        |   43 +++++++++++++++++++++++++++++++++++++++----
 2 files changed, 46 insertions(+), 8 deletions(-)

commit e163fdd92acdf7a903fce2a1e5249dd386ff712c
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Thu Mar 26 20:26:46 2009 +0100

    wii: enhance bootwrapper entry

    The bootloaders used on the Nintendo Wii may load the kernel and
    transfer control to it in a variety of environments.

    This patch modifies the entry point of the bootwrapper to not make any
    particular assumption about the initial state of the MMU.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/boot/wii.c |   98 ++++++++++++++++++++++++++++++++++++++++-------
 1 files changed, 84 insertions(+), 14 deletions(-)

commit 8034bd01f7068191d0f1044e942b8067d4f046e1
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Wed Mar 25 00:14:18 2009 +0100

    flipper-pic: add quiesce method

    Add a quiesce method to the "flipper" interrupt controller driver to
    inhibit all interrupt sources before a restart or kexec.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/platforms/embedded6xx/flipper-pic.c |   24 +++++++++++++++++++--
 arch/powerpc/platforms/embedded6xx/flipper-pic.h |    1 +
 arch/powerpc/platforms/embedded6xx/wii.c         |    1 +
 3 files changed, 23 insertions(+), 3 deletions(-)

commit c75c681771ab387ee53ca6cfaed9a432ee99f0d9
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Wed Mar 25 00:05:33 2009 +0100

    exi: add quiesce method

    Add a quiesce method to the EXternal Interface (EXI) driver to calm down
    the EXI hardware before a restart or kexec.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/platforms/embedded6xx/wii.c |    3 ++-
 drivers/exi/exi-driver.c                 |   10 ++++++++++
 drivers/exi/exi-hw.c                     |    5 +++++
 drivers/exi/exi-hw.h                     |    2 ++
 include/linux/exi.h                      |   12 ++++++++++++
 5 files changed, 31 insertions(+), 1 deletions(-)

commit f063156b4a5ff84206d0b79a5ae25d50262fc010
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Wed Mar 25 00:27:19 2009 +0100

    gcn-si: add shutdown method

    Add a shutdown method to the Serial Interface (SI) driver to quiesce
    the SI hardware before a restart or kexec.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 drivers/input/si/gcn-si.c |   31 +++++++++++++++++++++++++++----
 1 files changed, 27 insertions(+), 4 deletions(-)

commit afebd827733d7a76f323a59c8797b983d9e3655f
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Sat Mar 28 14:37:11 2009 +0100

    gcn-vi: re-detect tv mode if cable type changes

    Force a video mode detection cycle when setting up a video mode if the cable
    type has changed (component vs non-component).

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 drivers/video/gcnfb.c |   27 ++++++++++++++++++---------
 1 files changed, 18 insertions(+), 9 deletions(-)

commit 584224e2479475edb51a399b419205f7e2368bc2
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Tue Mar 24 23:56:48 2009 +0100

    gcn-vi: add shutdown method

    Add a shutdown method to the Video Interface (VI) driver to quiesce
    the VI hardware before a restart or kexec.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 drivers/video/gcnfb.c |   19 +++++++++++++++++++
 1 files changed, 19 insertions(+), 0 deletions(-)

commit a6e357287734b326ce05de38f8588fc4526d11a5
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Tue Mar 24 23:46:03 2009 +0100

    gcn-vi: reset video hardware before initiating detection

    Issue a hardware reset of the Video Interface (VI) hardware before
    performing the TV video mode autodetection.
    This fixes graphics glitches (swapped colors, green-red artifacts) seen after
    an incomplete video initialization.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 drivers/video/gcnfb.c |   11 +++++++++++
 1 files changed, 11 insertions(+), 0 deletions(-)

commit 2d13698e4014c461351658ee3a2c3f923f51cf3a
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Tue Mar 24 21:11:38 2009 +0100

    wii: platform restart rework

    Use the new IOS reload helpers in the platform restart code
    and kexec path.

    A platform restart tries now to load The Homebrew Channel and falls back
    to a normal STM restart if the former fails.
    On the other hand, the kexec reboot path reloads IOS before the final
    kexec phase to ensure that the kexec'ed image will get IOS in a known
    clean state.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/include/asm/starlet.h       |    2 +
 arch/powerpc/platforms/embedded6xx/wii.c |   36 ++++++++++++++++++++++++-----
 2 files changed, 31 insertions(+), 7 deletions(-)

commit e11bbe78fc0c212db0ff18553dbf7841e190f828
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Tue Mar 24 20:38:02 2009 +0100

    wii: starlet/ios: add ios reload helpers

    Add helpers for reloading IOS and optionally launching titles from NAND.

    These helpers will be used later in the platform code to implement a
    clean "direct reboot to channel" method, which finally will allow
    rebooting to The Homebrew Channel.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/include/asm/starlet.h              |    5 ++
 arch/powerpc/platforms/embedded6xx/starlet-es.c |   86 +++++++++++++++++++++++
 2 files changed, 91 insertions(+), 0 deletions(-)

commit e4d9d4e747632a6657f650c537e6e10a06f2747b
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Tue Mar 24 20:25:42 2009 +0100

    wii: starlet/ios: use polled ipc api on title launch

    This patch converts the title launch helper code to the new polled IPC
    call interface, and prepares it to be called from non-sleeping contexts.

    This change is required to implement later the new IOS reload helpers.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/platforms/embedded6xx/starlet-es.c |  184 +++++++++++------------
 1 files changed, 89 insertions(+), 95 deletions(-)

commit e09ea011b5c14e16b6498d7063abf54751901878
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Tue Mar 24 20:08:26 2009 +0100

    wii: starlet/ios: use polled ipc api on platform restart

    This patch fixes some known restart failure scenarios by switching the
    platform restart code to the new polled IPC call interface.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/platforms/embedded6xx/starlet-stm.c |   25 ++++++++++++++++-----
 1 files changed, 19 insertions(+), 6 deletions(-)

commit 644ec5f6c15bbdb275bd9b485f7a811d8eb67e2b
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Tue Mar 24 19:57:08 2009 +0100

    wii: starlet/ios: add polled ipc api

    Add a new set of functions enabling the use of IOS IPC calls from
    non-sleeping contexts or critical paths.

    The *_polled functions actively sample the status of their related IPC
    requests until they complete.
    Execution of this family of calls is serialized and use processor resources
    so they should be only used for very specific contexts where the other
    existing functions are not suitable.

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 arch/powerpc/include/asm/starlet.h               |   37 +++--
 arch/powerpc/platforms/embedded6xx/starlet-ipc.c |  197 +++++++++++++++++-----
 2 files changed, 179 insertions(+), 55 deletions(-)

commit fc5f68b629dbe6706fbabedf15e340428b196d5e
Author: Albert Herranz <albert_herranz@yahoo.es>
Date:   Tue Mar 10 18:14:20 2009 +0100

    gcn-si: fix named module parameter declaration

    This patch fixes the following build error due to an incorrect module
    parameter declaration.

    drivers/input/si/gcn-si.c:130: error: expected ')' before 'int'
    make[2]: *** [drivers/input/si/gcn-si.o] Error 1
    make[1]: *** [drivers/input/si] Error 2
    make: *** [drivers] Error 2

    Signed-off-by: Albert Herranz <albert_herranz@yahoo.es>

 drivers/input/si/gcn-si.c |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)